# Generated by Django 4.2.4 on 2023-08-17 10:45

from django.db import migrations, models
import django.utils.timezone
import django_tg_bot_framework.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_params', models.JSONField(blank=True, help_text='Дополнительные параметры того состояния, в котором сейчас находится диалог с пользователем.', null=True, verbose_name='Параметры состояния')),
                ('tg_username', models.CharField(blank=True, db_index=True, help_text='Имя для поиска человека в Telegram. Обычно выглядит так: @username. Вводите без символа @. Поле может быть пустым, если у пользователя tg не указан username.', max_length=50, validators=[django_tg_bot_framework.models.validate_tg_username_friendly_to_user], verbose_name='Имя юзера в Tg')),
                ('tg_user_id', models.CharField(db_index=True, help_text="Пример: 123456789. Чтобы узнать ID пользователя, перешлите сообщение пользователя боту <a href='https://t.me/userinfobot'>@userinfobot</a>.", max_length=50, verbose_name='Id юзера в Tg')),
                ('state_class_locator', models.CharField(blank=True, help_text='Тип состояния, в котором сейчас находится диалог с пользователем. В поле хранится локатор класса состояния, похожий на строку адреса URL. Локатор начинается со слэша <code>/</code> и заканчивается слэшом <code>/</code>, содержит только латинские символы a-z, цифры, знаки тире, подчёркивания и слэша <code>/</code>. Строго нижний регистр букв.', max_length=300, validators=[django_tg_bot_framework.models.validate_state_class_locator_friendly_to_user], verbose_name='Класс состояния')),
                ('tg_chat_id', models.CharField(db_index=True, help_text='Id чата в Tg, где пользователь общается с ботом.', max_length=50, unique=True, verbose_name='Id чата в Tg')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Диалог начинается, когда пользователь присылает боту своё первое сообщение в Tg.', verbose_name='когда начат')),
            ],
            options={
                'verbose_name': 'Диалог',
                'verbose_name_plural': 'Диалоги',
            },
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(check=models.Q(('state_class_locator__regex', '^/([a-z0-9_\\-]+/)*$'), ('state_class_locator', ''), _connector='OR'), name='correct_state_class_locator_format'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(check=models.Q(('tg_username__regex', '^[a-zA-Z0-9_]{5,50}$'), ('tg_username', ''), _connector='OR'), name='tg_username_correspond_to_spec'),
        ),
    ]
